# Generated by Django 4.2.6 on 2023-11-04 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_Name', models.CharField(max_length=50)),
                ('category_Description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(max_length=20)),
                ('order_date', models.CharField(max_length=20)),
                ('shipping_address', models.CharField(max_length=20)),
                ('billing_address', models.CharField(max_length=20)),
                ('tracking_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.CharField(max_length=20)),
                ('expiringDate', models.CharField(max_length=20)),
                ('cardNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Description', models.CharField(max_length=20)),
                ('product_Stock', models.CharField(max_length=20)),
                ('product_Rating', models.CharField(max_length=20)),
                ('product_picture', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('product_status', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_picture', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=20)),
                ('user_status', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_price', models.CharField(max_length=20)),
                ('date_added', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(max_length=20)),
                ('shipping_cost', models.CharField(max_length=20)),
                ('estimated_delivery', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.shoppingcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.user'),
        ),
    ]
