# Generated by Django 4.2.6 on 2023-10-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='REST',
            new_name='Drinks',
        ),
    ]
