# Generated by Django 4.2.6 on 2023-10-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_rest_drinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_Name', models.CharField(max_length=50)),
                ('category_Description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(max_length=20)),
                ('paymentID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('expiringDate', models.CharField(max_length=20)),
                ('cardNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_Description', models.CharField(max_length=20)),
                ('product_Stock', models.CharField(max_length=20)),
                ('product_Rating', models.CharField(max_length=20)),
                ('product_picture', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('product_status', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=20)),
                ('product_Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.category')),
            ],
        ),
        migrations.CreateModel(
            name='shoppingCarts',
            fields=[
                ('cartID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_price', models.CharField(max_length=20)),
                ('date_added', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_picture', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=20)),
                ('user_status', models.CharField(max_length=20)),
                ('user_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.AddField(
            model_name='shoppingcarts',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.user'),
        ),
    ]
