# Generated by Django 4.2.6 on 2023-11-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_alter_cartitem_cart_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingDetails',
            new_name='ShippingDetail',
        ),
    ]
