# Generated by Django 4.2.6 on 2023-11-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_rename_shippingdetails_shippingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
