# Generated by Django 4.2.6 on 2023-11-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture_width',
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
