# Generated by Django 4.2.6 on 2023-11-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_remove_product_picture_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_Rating',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_Stock',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_status',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
