# Generated by Django 4.2.6 on 2023-11-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lname',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='status',
        ),
    ]
