# Generated by Django 4.2.6 on 2023-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
