# Generated by Django 4.2.6 on 2023-11-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_remove_product_price_product_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('amount', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
            ],
        ),
    ]
