# Generated by Django 4.2.6 on 2023-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_newcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollection',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3),
        ),
    ]
