# Generated by Django 4.2.6 on 2023-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_alter_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollection',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
