# Generated by Django 4.2.6 on 2023-11-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0025_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
