# Generated by Django 4.2.6 on 2023-11-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcollection',
            name='description',
            field=models.CharField(default='no description', max_length=20),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='manufacturer',
            field=models.CharField(default='no manufacturer', max_length=20),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='name',
            field=models.CharField(default='no name', max_length=20),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='status',
            field=models.CharField(default='no satus', max_length=20),
        ),
        migrations.AddField(
            model_name='newcollection',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
