# Generated by Django 4.2.6 on 2023-11-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_newcollection_description_newcollection_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcollection',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newcollection',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newcollection',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
