from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from .Product.views import ProductView

router = routers.DefaultRouter()
router.register("Product", ProductView, basename="Product")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),  # Include the URLs generated by the router under the 'api/' path.
]
